package architecture_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestArchitecture_ProtocolPinningHasStableMakeCommands(t *testing.T) {
	contents, err := os.ReadFile(filepath.Join(repositoryRoot(t), "Makefile"))
	if err != nil {
		t.Fatalf("read Makefile: %v", err)
	}
	makefile := string(contents)
	for _, target := range []string{"protocol-sync:", "protocol-check:"} {
		if !strings.Contains(makefile, target) {
			t.Errorf("Makefile is missing %s", target)
		}
	}
	if !strings.Contains(makefile, "COMIS_ROOT") || !strings.Contains(makefile, "COMIS_COMMIT") {
		t.Error("protocol sync must require an explicit source root and commit")
	}
}

func TestArchitecture_GeneratedComisClientIsOwnedAndClosed(t *testing.T) {
	generatedPath := filepath.Join(repositoryRoot(t), "internal", "comiswire", "protocol.gen.go")
	contents, err := os.ReadFile(generatedPath)
	if err != nil {
		t.Fatalf("read generated Comis client: %v", err)
	}
	source := string(contents)
	if !strings.HasPrefix(source, "// Code generated by comiswire generator. DO NOT EDIT.\n") {
		t.Fatal("Comis wire output lacks generated ownership marker")
	}
	for _, forbidden := range []string{"func (client *Client) Call(", "func (client *Client) Activate(", "func (client *Client) Abandon("} {
		if strings.Contains(source, forbidden) {
			t.Fatalf("generated service client exposes forbidden authority: %q", forbidden)
		}
	}
}
