package generator

import (
	"bytes"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateProducesDeterministicClosedPinnedClient(t *testing.T) {
	protocolRoot := filepath.Join("..", "..", "..", "protocol", "comis")
	first, err := Generate(protocolRoot)
	if err != nil {
		t.Fatalf("generate pinned client: %v", err)
	}
	second, err := Generate(protocolRoot)
	if err != nil {
		t.Fatalf("repeat pinned generation: %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("identical pinned inputs produced different Go source")
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "protocol.gen.go", first, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v", err)
	}

	source := string(first)
	for _, required := range []string{
		"// Code generated by comiswire generator. DO NOT EDIT.",
		`ProtocolID = "comis.capability-service/1"`,
		`BundleDigest = "94ec7bd173cd20f0de2cb4e9ab719d392f240236ac80d56e3a7ea1abe4e20cb8"`,
		`MethodManagedRunsTerminalEvent`,
		"type WorkspaceLeaseID string",
		"type TerminalSessionID string",
		"type ExecutionAttachmentID string",
		"type AttachmentTargetName string",
		"type CapabilityTerminalTransition string",
		"type ExecutionAttachmentKind string",
		"ServiceScopeWorkspaceLease",
		"ServiceScopeTerminalEvents",
		"ServiceScopeExecutionAttachment",
		"type AbandonDisposition string",
		"type AbandonTerminalTransition string",
		"WorkspaceLeaseID      *WorkspaceLeaseID      `json:\"workspaceLeaseId,omitempty\"`",
		"AbandonDisposition `json:\"disposition\"`",
		"AbandonTerminalTransition `json:\"terminalTransition\"`",
		"type HandshakeRequestParams struct",
		"type HealthResponseResult struct",
		"type ActivateRequestParams struct",
		"ExecutionAttachmentID *ExecutionAttachmentID `json:\"executionAttachmentId,omitempty\"`",
		"AttachmentTargetName  *AttachmentTargetName  `json:\"attachmentTargetName,omitempty\"`",
		"type AbandonRequestParams struct",
		"type ReportRequestParams struct",
		"type TerminalEventRequestParams struct",
		"type TerminalEventResponseResult struct",
		"type MCPCallContext struct",
		"type MCPManagedRunResult struct",
		"type MCPManagedRunResultRequestedAttachment struct",
		"type RPCError struct",
		"func (client *Client) Handshake(",
		"func sameServiceScopeSet(",
		"func (client *Client) Health(",
		"func (client *Client) Report(",
	} {
		if !strings.Contains(source, required) {
			t.Errorf("generated source is missing %q", required)
		}
	}
	for _, forbidden := range []string{
		"func (client *Client) Call(",
		"func (client *Client) Activate(",
		"func (client *Client) Abandon(",
	} {
		if strings.Contains(source, forbidden) {
			t.Errorf("generated client exposes forbidden method %q", forbidden)
		}
	}
}

func TestGenerateRejectsChangedPinnedIdentityAndDigest(t *testing.T) {
	protocolRoot := filepath.Join("..", "..", "..", "protocol", "comis")
	for _, test := range []struct {
		name string
		old  string
		new  string
	}{
		{name: "protocol identifier", old: "comis.capability-service/1", new: "comis.capability-service/2"},
		{name: "bundle digest", old: "94ec7bd173cd20f0de2cb4e9ab719d392f240236ac80d56e3a7ea1abe4e20cb8", new: strings.Repeat("0", 64)},
	} {
		t.Run(test.name, func(t *testing.T) {
			copyRoot := filepath.Join(t.TempDir(), "comis")
			copyProtocolTree(t, protocolRoot, copyRoot)
			provenancePath := filepath.Join(copyRoot, "provenance.json")
			contents, err := os.ReadFile(provenancePath)
			if err != nil {
				t.Fatalf("read copied provenance: %v", err)
			}
			contents = []byte(strings.Replace(string(contents), test.old, test.new, 1))
			if err := os.WriteFile(provenancePath, contents, 0o644); err != nil {
				t.Fatalf("change copied provenance: %v", err)
			}
			if _, err := Generate(copyRoot); err == nil {
				t.Fatal("expected changed pin rejection")
			}
		})
	}
}

func copyProtocolTree(t *testing.T, source, destination string) {
	t.Helper()
	err := filepath.WalkDir(source, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		relative, err := filepath.Rel(source, path)
		if err != nil {
			return err
		}
		target := filepath.Join(destination, relative)
		if entry.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		contents, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, contents, 0o644)
	})
	if err != nil {
		t.Fatalf("copy protocol tree: %v", err)
	}
}
