// Package generator emits the adapter-local Go contract from the authenticated pin.
package generator

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/comisai/comis-dev-crew/internal/comiswire/bundle"
)

const (
	expectedProtocolID = "comis.capability-service/1"
	pinnedSchemaCount    = 34
	expectedBundleDigest = "b42ab7a7662f3b02ede4d12d55e1ae7d50855990897fc4d24164b3a35f3c711d"
)

// Generate verifies the exact pin and deterministically renders its Go DTOs and client.
func Generate(protocolRoot string) ([]byte, error) {
	pin, err := bundle.OpenPinned(protocolRoot)
	if err != nil {
		return nil, fmt.Errorf("verify protocol pin: %w", err)
	}
	if pin.Manifest.ProtocolID != expectedProtocolID || pin.Manifest.BundleDigest != expectedBundleDigest {
		return nil, fmt.Errorf("protocol identity or digest differs from the accepted pin")
	}
	schemas, err := loadSchemas(pin)
	if err != nil {
		return nil, err
	}
	contract, err := renderContract(pin.Manifest, schemas)
	if err != nil {
		return nil, err
	}
	types, err := renderTypes(schemas)
	if err != nil {
		return nil, err
	}
	client, err := renderClient(pin.Manifest)
	if err != nil {
		return nil, err
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by comiswire generator. DO NOT EDIT.\n\n")
	source.WriteString("package comiswire\n\n")
	source.WriteString("import (\n\t\"context\"\n\t\"crypto/sha256\"\n\t\"encoding/base64\"\n\t\"fmt\"\n)\n\n")
	source.WriteString(contract)
	source.WriteString(types)
	source.WriteString(client)
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go source: %w", err)
	}
	return formatted, nil
}
